# https://github.com/grafana/helm-charts/tree/main/charts/grafana
apiVersion: helm.kustomize.mgoltzsche.github.com/v1
kind: ChartRenderer
metadata:
  name: grafana
  namespace: monitoring-system
# repository: ./
repository: https://grafana.github.io/helm-charts # https://github.com/grafana/helm-charts
# chart: ./Sources/monitoring-system/grafana/
# chart: file:///workdir/Sources/monitoring-system/grafana/grafana
chart: grafana
version: 5.6.7
valueFiles:
- grafana-chart-values.yml
