title: Cloud Native Thermostat Guide
description: Living documentation of home made thermostat
show_downloads: false
is_project_page: false
google_analytics:
theme: noir-for-jekyll
logo: thermometer.png

defaults:
  - 
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

# github_link: "https://github.com/Cloud-Native-Thermostat/Guide"
# blog_link: "https://cloud-native-thermostat.github.io/Guide/"
# website_link: "https://cloud-native-thermostat.github.io/Guide/"
baseurl: "/Guide" # the subpath of your site, e.g. /blog
url: "https://cloud-native-thermostat.github.io/Guide/" # the base hostname & protocol for your site, e.g. http://example.com
plugins:
- jekyll-gist
- jekyll-paginate
- jekyll-seo-tag
- jekyll-target-blank
- jekyll-readme-index

readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: true
