apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: node-exporter
  namespace: monitoring-system
spec:
  selector:
    matchLabels:
      app: prometheus-node-exporter
  endpoints:
  - port: metrics
