# n2
ssh_authorized_keys:
- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC8NJzXwljIAD6A0M9S6o2JFSYVuRB0S16VR5Pc96KisuBD5gg8tZs3591KEwHxQJdR6ES1yEFTuVtGfs2UewjMkAspdw+MMPn7B/DjJz1bm7YXNKzC9U3pebkQDpt3l4fKyoGxkgCxe6XxO7W72xR5hsDZg216YZlTBXbhb4pfSIxicooOtk+VvHfboL2jqLEVfa8WsCIveLtzb7FuJPSJRHFG/IlmbxmGqtmLe6G68SojIRiT7kIrWE1DcM7DU/uw3clwky43JGBqTglH8FIfAlvRZtRC+MKSg4KBt8b2zqDjj1zetX+w9Bgfb/aGAMgCHmJn5ZYnru1bBSV58NiKg2ZJ3KREj2M8cPjCzL+VkAAivdgTC/JC1QjtYsOc1JT2VIUqaP0p8RDaGvIK79mAkfOEJAJuanBdzqrI+qTqFcSg3bcqSITtboBRIfXxY4aeQzkIgEUZ1bdim0hXOPIAnQjT2/N3Q319WDvoSkiZzKRFPbrUXFp+eh58DjLUrO7UlEW1evhDIh5Q3l6ItDaUucQYc3tjfEf3A+SF48vLpaHb3uo9afnlUEbg1Q4gztbcgtbdc9jE2r6hhgiF9KnUdKR/pOs8uR7PHdXeugGj9bnCePezeshNyFdOOJhOND7QnPo+em8fTGC+5in7vbJSrEm3N+/BXGtTgdo2zNkfcw== mario@vejlupek.cz
hostname: n2
k3os:
  ntp_servers:
  - 10.236.64.1
  k3s_args:
  - agent
  token: K9e4255df5cb259e4255df26204f0250d6fec0ce8f29b0627c6f59f5cb259e4255::server:d78af32afab244a848bca151a256ec9b
  server_url: https://MASTER_1_IP:6443
